artifact_location: file:///C:/Users/TNEL/Documents/GitHub/mlops-image-classifier/runs/mlflow/296165229416536266
creation_time: 1749165257713
experiment_id: '296165229416536266'
last_update_time: 1749165257713
lifecycle_stage: active
name: runs/classifier
