artifact_location: file:///C:/Users/TNEL/Documents/GitHub/mlops-image-classifier/runs/mlflow/0
creation_time: 1749165257690
experiment_id: '0'
last_update_time: 1749165257690
lifecycle_stage: active
name: Default
